on:
  workflow_call:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        type: string

permissions:
  contents: read
  actions: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20.18.3
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Create .env file
        run: |
          echo "API_URL=${{ vars.API_URL }}" >> .env
          echo "BODY_SIZE_LIMIT=${{ vars.BODY_SIZE_LIMIT }}" >> .env
          echo "ORIGIN=${{ vars.ORIGIN }}" >> .env

      - name: Build website
        run: npm run build

      - name: Copy entrypoint script
        run: |
          mkdir -p build/build
          rsync -av --exclude 'build/' build/ build/build/
          cp entry.cjs build/entry.cjs

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
          include-hidden-files: true
