name: disable branch protection rules

on:
  workflow_call:
    inputs:
      branch:
        type: string
        description: 'Branch to checkout'
        required: true
    secrets:
      TOKEN:
        required: true
  workflow_dispatch:

jobs:
  disable_branch_protection:
    name: Disable Branch Protection
    runs-on: ubuntu-latest
    steps:
      - name: Disable branch protection rules
        run: |
          curl -L \
          -X DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/branches/${{ inputs.branch || github.ref }}/protection
