name: enable branch protection rules

on:
  workflow_call:
    inputs:
      branch:
        type: string
        description: 'Branch to checkout'
        required: true
      lock:
        type: boolean
        description: 'Lock the branch'
        default: true
        required: false

    secrets:
      TOKEN:
        required: true
  workflow_dispatch:
    inputs:
      lock:
        type: boolean
        description: 'Lock the branch'
        default: true
        required: false

jobs:
  enable_branch_protection:
    name:
    runs-on: ubuntu-latest
    steps:
      - name: Enable branch protection rules
        run: |
          curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/branches/${{ inputs.branch || github.ref }}/protection \
            -d '{"required_status_checks":{"strict":true,"contexts":[]},"enforce_admins":true,"required_pull_request_reviews":{"dismissal_restrictions":{"users":[],"teams":["admin"]},"dismiss_stale_reviews":true,"require_code_owner_reviews":true,"required_approving_review_count":1,"require_last_push_approval":false,"bypass_pull_request_allowances":{"users":[],"teams":["admin"]}},"restrictions":null,"required_linear_history":true,"allow_force_pushes":false,"allow_deletions":false,"block_creations":true,"required_conversation_resolution":true,"lock_branch":${{inputs.lock}},"allow_fork_syncing":false}'

      - name: Allow admins to bypass branch protection rules
        if: ${{ !inputs.lock }}
        run: |
          curl -L \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/branches/${{ inputs.branch || github.ref }}/protection/enforce_admins
