name: Release Developpement

on:
  schedule:
    - cron: '0 5 * * *' # Every day at 5am UTC (adjust if needed)

  workflow_dispatch: # Allows manual triggering too

jobs:
  disable-protection:
    name: Deactivate Branch Protection
    uses: ./.github/workflows/_disable_protection.yml
    with:
      branch: release-dev
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}

  merge:
    runs-on: ubuntu-latest
    needs: disable-protection

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # important for git log
          ref: dev # checkout the developpement branch

      - name: Set up Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"

      - name: Delete release-dev branch if it exists
        run: |
          git fetch origin --prune
          if git show-ref --verify --quiet refs/heads/release-dev; then
            git push origin --delete release-dev
          fi

      - name: Create release-dev branch
        run: |
          git checkout -b release-dev
          git push origin release-dev

  activate-protection:
    name: Activate Branch Protection
    uses: ./.github/workflows/_enable_protection.yml
    needs: merge
    with:
      branch: release-dev
      lock: true
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
