name: Release Production

on:
  workflow_dispatch: # Allows manual triggering too

jobs:
  disable-protection:
    name: Deactivate Branch Protection
    uses: ./.github/workflows/_disable_protection.yml
    with:
      branch: release-prod
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}

  merge:
    runs-on: ubuntu-latest
    needs: disable-protection
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # important for git log
          ref: prod # checkout the production branch

      - name: Set up Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"

      - name: Delete release-production branch if it exists
        run: |
          git fetch origin --prune
          if git show-ref --verify --quiet refs/heads/release-prod; then
            git push origin --delete release-prod
          fi

      - name: Create release-production branch
        run: |
          git checkout -b release-prod
          git push origin release-prod

  activate-protection:
    name: Activate Branch Protection
    uses: ./.github/workflows/_enable_protection.yml
    needs: merge
    with:
      branch: release-prod
      lock: true
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
